### ISSUE TITLE
Split "Lexer" section up into multiple parts

### ISSUE THREAD

**Issue by Gigabyte-Giant** [BurstLanguage/Language-Specification#2]
As @anthony-y mentioned, tokenizing and lexing are slightly different, as discussed [here](http://stackoverflow.com/questions/380455/looking-for-a-clear-definition-of-what-a-tokenizer-parser-and-lexers-are/380487#380487).

**Comment by Gigabyte-Giant** [comment]
@anthony-y, does anything else need to be done for this?

**Comment by anthony-y** [comment]
Nothing I can think of off the top of my head. So for now it's done :D
